#!/usr/bin/env python3


import argparse
import subprocess

from time import monotonic
from typing import Final
from pathlib import Path


parser = argparse.ArgumentParser()
parser.add_argument("--day", type=int, required=False)
parsed_args = parser.parse_args()


PUZZLES_PATH: Final[Path] = Path("puzzles/")
SEARCH_DIRS: list[Path] = (
    [PUZZLES_PATH / f"day{parsed_args.day}"]
    if parsed_args.day
    else list(PUZZLES_PATH.iterdir())
)
for directory in SEARCH_DIRS:
    for part in directory.glob("*.go"):
        print(f"{directory.name}-{part.stem}:")
        subprocess.run(["go", "build", part])
        start = monotonic()
        subprocess.run([f"./{part.stem}"])
        print("Time spent for all: ", round(monotonic() - start, 5))
        Path(part.stem).unlink()
        print()
